sprg.application.name=user-service
server.port=8086

eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone= http://localhost:9099/eureka
management.endpoints.web.exposure.include=*
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.register-health-indicator=true
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.event-consumer-buffer-size=10
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.sliding-window-size=10
resilience4j.circuitbreaker.instances.USER_RATING_SERVICE.sliding-window-type=COUNT_BASED

resilience4j.retry.instances.USERRATINGRETRY.max-attempts=3
resilience4j.retry.instances.USERRATINGRETRY.wait-duration=3s

